// <auto-generated />
using System;
using Income.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Income.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IncomeDbContext))]
    [Migration("20260113101923_AddStreamTypeAndLinkedIncomeStreamId")]
    partial class AddStreamTypeAndLinkedIncomeStreamId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("income")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Income.Infrastructure.Persistence.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("StreamId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("stream_id");

                    b.Property<string>("StreamName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stream_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("ix_notifications_is_read");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_notifications_type");

                    b.ToTable("notifications", "income");
                });

            modelBuilder.Entity("Income.Infrastructure.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_schema");

                    b.Property<int>("ConnectorKind")
                        .HasColumnType("integer")
                        .HasColumnName("connector_kind");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("default_currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SyncFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("sync_frequency");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_providers_name");

                    b.ToTable("providers", "income");
                });

            modelBuilder.Entity("Income.Infrastructure.Persistence.Entities.SnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("original_amount");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("original_currency");

                    b.Property<string>("RateSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rate_source");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("stream_id");

                    b.Property<decimal>("UsdAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("usd_amount");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_snapshots_date");

                    b.HasIndex("StreamId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_snapshots_stream_date");

                    b.ToTable("snapshots", "income");
                });

            modelBuilder.Entity("Income.Infrastructure.Persistence.Entities.StreamEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedCredentials")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_credentials");

                    b.Property<string>("FixedPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fixed_period");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixed");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("LinkedIncomeStreamId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("linked_income_stream_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_scheduled_at");

                    b.Property<string>("OriginalCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("original_currency");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("provider_id");

                    b.Property<decimal?>("RecurringAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("recurring_amount");

                    b.Property<int?>("RecurringFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("recurring_frequency");

                    b.Property<DateOnly?>("RecurringStartDate")
                        .HasColumnType("date")
                        .HasColumnName("recurring_start_date");

                    b.Property<int>("StreamType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stream_type");

                    b.Property<int>("SyncState")
                        .HasColumnType("integer")
                        .HasColumnName("sync_state");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_streams_category");

                    b.HasIndex("LinkedIncomeStreamId")
                        .HasDatabaseName("ix_streams_linked_income_stream_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_streams_provider_id");

                    b.HasIndex("StreamType")
                        .HasDatabaseName("ix_streams_stream_type");

                    b.ToTable("streams", "income");
                });

            modelBuilder.Entity("Income.Infrastructure.Persistence.Entities.SnapshotEntity", b =>
                {
                    b.HasOne("Income.Infrastructure.Persistence.Entities.StreamEntity", "Stream")
                        .WithMany("Snapshots")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("Income.Infrastructure.Persistence.Entities.StreamEntity", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
