namespace Income.Application.Connectors;

/// <summary>
/// Connector that generates income snapshots based on a recurring schedule.
/// Used for fixed income like salary, rent, subscriptions, etc.
/// No external API calls - snapshots are auto-generated on schedule.
/// </summary>
public interface IRecurringConnector : IIncomeConnector
{
    /// <summary>
    /// Calculates the next payment date based on start date and frequency.
    /// </summary>
    DateOnly CalculateNextPaymentDate(
        DateOnly startDate,
        RecurringFrequency frequency,
        DateOnly asOfDate);

    /// <summary>
    /// Checks if a payment is due on the given date.
    /// </summary>
    bool IsPaymentDue(
        DateOnly startDate,
        RecurringFrequency frequency,
        DateOnly checkDate);

    /// <summary>
    /// Generates a snapshot for a recurring payment.
    /// </summary>
    RecurringSnapshotData GenerateSnapshot(
        decimal amount,
        string currency,
        DateOnly paymentDate);
}

/// <summary>
/// Data generated by a recurring connector for a scheduled payment.
/// </summary>
public sealed record RecurringSnapshotData(
    DateOnly Date,
    decimal OriginalAmount,
    string OriginalCurrency,
    decimal UsdAmount,
    decimal ExchangeRate,
    string RateSource);
